# Slicing of array

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])

In [3]:
arr[0:4]# this always include the start index and exlcude the end index

array([1, 2, 3, 4])

## negative slicing
- [-3:-4]

In [4]:
arr[-3:-1]

array([5, 6])

## step 
-use thestep valude to determine the steps of  slicing

In [5]:
arr[1:5:2]

array([2, 4])

# slicing in 2-D arrays

In [6]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10]])

In [7]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
arr[0,1:-1]

array([2, 3, 4])

In [9]:
arr[1,1:-2:2]

array([7])

In [10]:
arr[1,:-1:2]

array([6, 8])

## iterating arrays 


In [11]:
for x in arr:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


## data types in array

In [12]:
a1=np.array([1,3,4,5,5])

In [13]:
a1.dtype

dtype('int64')

In [14]:
a2=np.array(['a','b','c'])

In [15]:
a2.dtype

dtype('<U1')

In [16]:
a3=np.array([1,2,3,4,5],dtype='S')

In [17]:
a3.dtype

dtype('S1')

In [18]:
a4=np.array([1,3,4,5,6],dtype='i4')

In [19]:
a4.dtype

dtype('int32')

## Converting datatypes on existing arrays

In [20]:
a5=np.array([1.1,1.2,2.3,4.5])

In [22]:
newa5=a5.astype('i')

In [23]:
newa5

array([1, 1, 2, 4], dtype=int32)

In [24]:
nnew=newa5.astype(bool
                 )

In [25]:
nnew

array([ True,  True,  True,  True])

# Random number in numpy
-numpy offers the random modeule to work with random numbers

In [26]:
from numpy import random
x=random.randint(100)

In [27]:
x

54

## generate random float 
- the random module's rand() method reutrns a random float between 0 and 1.

In [28]:
x=random.rand()

In [29]:
x

0.21096043824823696

In [30]:
x1=random.rand()

In [31]:
x1

0.17029316390330518

## generate random array

In [32]:
x=random.randint(100,size=(5))

In [33]:
x

array([18, 14, 57, 91, 25], dtype=int32)

In [36]:
x=random.randint(100,size=(15))

In [37]:
x

array([ 1, 13,  3, 21, 55,  3,  3,  7, 76, 36,  8, 72, 90, 26, 88],
      dtype=int32)

### making 2 d arrays

In [38]:
x =random .randint(100,size=(3,4))

In [39]:
x

array([[ 0, 48, 31, 64],
       [77, 61, 30, 12],
       [67, 39, 47, 69]], dtype=int32)

## floats 
-rand() method also allow yout to specify the shape of the array 


In [40]:
x=random.rand(5)

In [41]:
x

array([0.98414743, 0.75005735, 0.57891281, 0.25340356, 0.892756  ])

In [42]:
x=random.rand(3,4)

In [43]:
x


array([[0.52394573, 0.86434787, 0.0801385 , 0.94711534],
       [0.32421452, 0.64292752, 0.42157591, 0.13468124],
       [0.15810069, 0.84207353, 0.94228135, 0.00991152]])