## Numpy array basics

In [3]:
import numpy as np

## creating array from list

In [4]:
arr1d=np.array([12,4,5,6])


In [5]:
print(arr1d)

[12  4  5  6]


## list vs numpy

In [6]:
list1=[1,2,3,4]
print("python list multiplication",list1*2)


python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]


In [7]:
print("numpy multiplication :",arr1d*2)

numpy multiplication : [24  8 10 12]


In [8]:
import time

In [9]:
start=time.time()
list1=[i*2 for i in range(100000)]
print("\n list operation time :",time.time()-start)


 list operation time : 0.007963180541992188


In [10]:
start=time.time()
arr2=np.arange(100000)
print("\n numpy operation time:",time.time()-start)



 numpy operation time: 0.0003800392150878906


## creating array from the scratch

In [11]:
zeros=np.zeros((3,4))
print("zeros array:\n",zeros)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
full=np.full((2,2),7)

In [14]:
full

array([[7, 7],
       [7, 7]])

In [15]:
random=np.random.random((2,3))

In [16]:
random

array([[0.43175663, 0.29295759, 0.66857712],
       [0.84155865, 0.12244034, 0.42340053]])

In [17]:
sequnce=np.arange(0,10)

In [18]:
sequnce

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
sequence=np.arange(1,100,2)

In [20]:
sequence

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## vector,matrics, tensor 

In [21]:
vector=np.array([1,2,3,4,5])
print("vector:",vector)

vector: [1 2 3 4 5]


In [22]:
matrix=np.array([[1,2,3],[4,5,6]])

In [23]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
tensor=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [26]:
tensor

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

## array properties 

In [27]:
arr=np.array([[1,2,3],[4,5,6]])

In [28]:
print("shape of  array:",arr.shape)

shape of  array: (2, 3)


In [29]:
arr.ndim

2

In [30]:
arr.size

6

In [31]:
arr.dtype

dtype('int64')

### array reshaping

In [39]:
arr=np.arange(0,12)

In [49]:
arr
print("original array:",arr)
reshaped = arr.reshape(3,4)
print("reshaped array:",reshaped)
flattened=reshaped.flatten()
print("flattened array:",flattened)
raveled=reshaped.ravel()
#ravel is similar to flatten but returns a view if possible
print("ravelled array",raveled)
# transpose 
transposed=reshaped.T
print("trnsposed array:\n",transposed)

original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravelled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
trnsposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
