## Numpy array basics

In [3]:
import numpy as np

## creating array from list

In [4]:
arr1d=np.array([12,4,5,6])


In [5]:
print(arr1d)

[12  4  5  6]


## list vs numpy

In [ ]:
list1=[1,2,3,4]
print("python list multiplication",list1*2)


python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]


In [7]:
print("numpy multiplication :",arr1d*2)

numpy multiplication : [24  8 10 12]


In [8]:
import time

In [9]:
start=time.time()
list1=[i*2 for i in range(100000)]
print("\n list operation time :",time.time()-start)


 list operation time : 0.00507807731628418


In [11]:
start=time.time()
arr2=np.arange(100000)
print("\n numpy operation time:",time.time()-start)



 numpy operation time: 0.0003352165222167969


## creating array from the scratch

In [14]:
zeros=np.zeros((3,4))
print("zeros array:\n",zeros)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
full=np.full((2,2),7)

In [17]:
full

array([[7, 7],
       [7, 7]])

In [19]:
random=np.random.random((2,3))

In [20]:
random

array([[0.21414485, 0.23073197, 0.20721981],
       [0.4454825 , 0.49660996, 0.87128742]])

In [21]:
sequnce=np.arange(0,10)

In [22]:
sequnce

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
sequence=np.arange(1,100,2)

In [24]:
sequence

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## vector,matrics, tenson