## Numpy array operations

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("basic slicing:",arr[2:7])
print("with step:",arr[2:-1:2])
print("negative indexing:",arr[-2])

basic slicing: [3 4 5 6 7]
with step: [3 5 7]
negative indexing: 8


In [3]:
arr2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("specific element:",arr2d[1,2])
print("entrire row:",arr2d[1])
print("third row:",arr2d[2])
print("entire column:",arr2d[:,1])
print("0 column:",arr2d[:,0])
print("3 rd column:",arr2d[:,2])

specific element: 6
entrire row: [4 5 6]
third row: [7 8 9]
entire column: [2 5 8]
0 column: [1 4 7]
3 rd column: [3 6 9]


## sorting

In [4]:
unsorted=np.array([3,4,1,6,7,8,13,56,78,44,100])

In [5]:
print("unsorted array",unsorted)

unsorted array [  3   4   1   6   7   8  13  56  78  44 100]


In [6]:
print('sorted array:',np.sort(unsorted))

sorted array: [  1   3   4   6   7   8  13  44  56  78 100]


In [7]:
arr_2d_unsorted=np.array([[1,10,22,4],
                          [3,55,6,1],
                          [6,8,3,7]])

In [8]:
print("sorted 2D array by column:",np.sort(arr_2d_unsorted,axis=0))

sorted 2D array by column: [[ 1  8  3  1]
 [ 3 10  6  4]
 [ 6 55 22  7]]


## 

## Filtering


In [9]:
numbers=np.arange(0,12)

In [10]:
print("numbers:",numbers)

numbers: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
even_numbers=numbers[numbers % 2==0]
print("even numbers:",even_numbers)
odd_numbers=numbers[numbers % 2!=0]
print("odd number:",odd_numbers)

even numbers: [ 0  2  4  6  8 10]
odd number: [ 1  3  5  7  9 11]


## Fiter with mask

In [12]:
mask=numbers>5
print("nubers greater than 5",numbers[mask])

nubers greater than 5 [ 6  7  8  9 10 11]


In [13]:
num=numbers<10

In [14]:
print("number less than 10",numbers[num])

number less than 10 [0 1 2 3 4 5 6 7 8 9]


## fancy indexing and np.where()

In [15]:
index=[0,1,4,6,5]
print(numbers[index])
where_result=np.where(numbers>5)
print("where result",where_result)

[0 1 4 6 5]
where result (array([ 6,  7,  8,  9, 10, 11]),)


In [17]:
condition_array=np.where(numbers > 5,numbers*4,numbers)
print(condition_array)

[ 0  1  2  3  4  5 24 28 32 36 40 44]


### Adding and Removing the data


In [18]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [19]:
combined=arr1 + arr2

In [20]:
combined

array([5, 7, 9])

In [23]:
combined=np.concatenate((arr1,arr2))


In [24]:
combined

array([1, 2, 3, 4, 5, 6])

### array compatibility

In [29]:
a=np.array([1,2,3])
b=np.array([4,5,6,5])
c=np.array([7,8,9])

In [30]:
print("compatibility shape",a.shape==b.shape)

compatibility shape False


In [32]:
print("compacitbility shape:",a.shape==c.shape)

compacitbility shape: True


In [42]:
original=np.array([[1,2],[3,4]])

In [43]:
new_row=np.array([[5,6]])

In [44]:
with_new_row=np.vstack((original,new_row))

In [45]:
with_new_row

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
new_col=np.array([[8],[9]])

In [47]:
with_new_col=np.hstack((original,new_col))

In [49]:
print("with new column:",with_new_col)

with new column: [[1 2 8]
 [3 4 9]]


In [52]:
arr=np.array([1,3,4,4,5,5])
deleted=np.delete(arr,2)
print("array after deletion :",deleted)

array after deletion : [1 3 4 5 5]
